### ISSUE TITLE
Globally remove advertisements from all pages

### ISSUE THREAD

**Issue by ekstroem** [mmistakes/skinny-bones-jekyll#19]
Hi,

Is is possible to remove the advertisements globally from all pages (e.g., posts) in order to user the full screen. I tried entering ```ads: false``` as shown below in ```_config.yml```but it doesn't seem to have the desired effect.

```
# Site owner
owner:
  name: 
  email: 
  twitter: 
  google:
    ad-client: 
    ad-slot: 
    ads: false
  bio: 
  avatar: bio-photo.jpg # 160x160 px image for author byline
```
