### ISSUE TITLE
Modified date

### ISSUE THREAD

**Issue by tclose** [mmistakes/skinny-bones-jekyll#25]
Hi MIchael,

Nice templates! I just have a few questions on how to use them properly the first of which is getting the modified date to show up properly. I have this "article" md file at "/by-laws/"

```
---
layout: article
title: "By-laws"
modified: 2014-10-02
image:
  feature:
  teaser:
  thumb:
share: false
toc: false
---

test
```

which shows up fine but doesn't include the modified date, what am I missing?
